### ISSUE TITLE
Wait until file is no longer being written to in imagery service file backend

### ISSUE THREAD

**Issue by bloof-bb** [uavaustin/orchestra#15]
If a particularly large image is being copied over, there's a good chance that the the file will be read in before another process is done copying the file into that directory. I'm pretty sure this is the problem since dropping an image in that folder is giving me either the full size image, or smaller images of varying sizes which are chopped off a bit and aren't rendering well.

Just before running [this step](https://github.com/uavaustin/orchestra/blob/41bf0c81e0d4872259bad8d27cd8b50db756533c/services/imagery/src/backends/file-backend.js#L38) is where we'll need to make sure the file isn't being written to before preceding.

**Comment by oldmud0** [comment]
Yeah... I thought there would be a way to read in a file like a FIFO pipe (i.e. as it is being written to, `tail -f` style) but you can only have one or the other. Even `tail -f` has to use inotify to work efficiently, and that is a Linux-only feature.

**Comment by bloof-bb** [comment]
Yeah I'm having a problem finding a graceful way to solve this one, what some people recommend (though it's kinda hacky in a way) is just to wait a little bit and see if the file got larger, if it didn't, then you're good to go.

**Comment by oldmud0** [comment]
If you want to really make sure you are not reading a file while it is written to, a lock file would probably be best.

**Comment by bloof-bb** [comment]
Yeah instead of just `cp`-ing a file over directly, doing something like:
```sh
cp picture.png orchestra/test/data/new-images/picture.png.tmp
mv orchestra/test/data/new-images/picture.png.tmp orchestra/test/data/new-images/picture.png
```
is enough to prevent the problem from happening, but it's still kinda gross in a way that you have to do that.

**Comment by oldmud0** [comment]
also possible:

```
touch orchestra/test/data/new-images/picture.png.lck
cp picture.png orchestra/test/data/new-images/picture.png
rm orchestra/test/data/new-images/picture.png.lck
```

**Comment by bloof-bb** [comment]
Since this is only really being used for testing, and just moving a file into the folder instead of copying works, I'll go ahead and close this.

For the lock file part, that would require editing some of the source which takes more work to implement.
