### ISSUE TITLE
Limit how many images are stored in imagery service

### ISSUE THREAD

**Issue by bbridges** [uavaustin/orchestra#19]
Since images can be pretty large, there is a risk of storing too many images on our devices if the service is running for too long. Having an environment variable set how many images can be stored until old ones are removed will help with this significantly. We'll need to 404 if an old image is trying to be fetched and it's not available, the sync backend will have to make sure it just skips this. Because of skips, we can just make the image id numbers consistent across each service so all the skips will be the same.

**Comment by bloof-bb** [comment]
This might not be too much a problem since JPEG images are being used anyways, if we do actually come across a case where we do fill up our storage on the plane, then this can be revisited.
