### ISSUE TITLE
Handle sending empty missions to the plane

### ISSUE THREAD

**Issue by bloof-bb** [uavaustin/orchestra#23]
If a request is made to `POST /api/raw-mission` in the telemetry service with an empty array for `mission_items`, the service gets stuck because the plane keeps sending requests for waypoint 0. Instead, doing this should just clear the mission.

See `services/telemetry/test/data/test-raw-mission-3.json`.

**Comment by oldmud0** [comment]
Should be fixed in 78fad02d8907e4ac8188466ff65497dfad5a78a0, which passes `test-raw-mission-3.json`.
